version: '3.1'

services:
  
  db:
    image: mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
    ports:
      - "3307:3306"
    volumes:
      - ./sql/src:/usr/src
      - ./sql/mysql:/var/lib/mysql